### ISSUE TITLE
License this project is distributed under

### ISSUE THREAD

**Issue by ShamrockLee** [cms-sw/cms-common#7]
[CMSSW](https://github.com/cms-sw/cmssw/blob/master/LICENSE) is distributed under the Apache License 2.0, and [SCRAM](https://github.com/cms-sw/SCRAM/blob/SCRAMV3/LICENSE) is distributed under the MIT License.

As a collection of generic helpers of the above open source projects, it would be a pity for it to be proprietary.

Is cms-common an open source project? If so, which license is it distributed under?

Either way, it would be nice to have a LICENSE or COPYING at the top of the project to make it clear for people visiting it.

**Comment by makortel** [comment]
@smuzaffar Any thoughts?

**Comment by smuzaffar** [comment]
@makortel , I think we can add `Apache License 2.0` for this repo too.

**Comment by smuzaffar** [comment]
added `Apache License 2.0` https://github.com/cms-sw/cms-common/blob/master/LICENSE
